ALTER TABLE interview_sessions
  MODIFY COLUMN role ENUM('BACKEND','FRONTEND','DATA','PM') NOT NULL,
  MODIFY COLUMN difficulty ENUM('EASY','MEDIUM','HARD') NOT NULL,
  MODIFY COLUMN language ENUM('JAVA','PYTHON','JAVASCRIPT','SQL') NOT NULL;
